# User config
author: "Roosevelt"
tagline: ""
description: "Portfolio of my programming projects"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "roosevelt_stenson@yahoo.com"
linkedin: "https://www.linkedin.com/in/roosevelt-stenson-b65a8295/"
twitter: "https://twitter.com/PureNukage"
github: "https://github.com/PureNukage"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed